model:
    batch_size: 256
    num_epochs: 1
    lr: 0.001
    input_size: 784
    num_classes: 10
    model_path: 'mnist-logistic.pth'
    model_path_onnx: 'mnist-logistic.onnx'

logger:
    exp: 'exp_mnist'
    path: 'file:./logs'
